import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nini Portfolio",
  icons: [process.env.__PATH + "/favicon24.ico",],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
